riot_pal/dut_shell.py: changed the DutShell to case-insensitive anwser messages
RIOT-OS/riot_pal pull request #32
Opened 2019-10-18 13:15 UTC by jan-mo

in RIOT-OS there are some shell-commands which are answering with lower case, like ifconfig (sys/shell/commands/sc_gnrc_netif.c). The answer look like "success: " but DutShell is waiting for "Success: ". So I only changed the if-statements to compare the lower cases of response and value to make it case-insensitive.

2019-10-18 13:31 UTC, MrKevinWeiss commented
I don't think the dut_shell was designed for sc_gnrc_netif or vice versa.

The reason we wanted it to be `Success` is so that it is defined. The approach I would take is to make everything that uses the DutShell to adhere to that, so we have a sort of standard approach.  With `success` or `SUCCESS` or even `PASS` or `OK` we have this ambiguity.

I tried to touch this in the https://github.com/RIOT-OS/RIOT/pull/10624 rdm but other things got in the way...

Are you writing other tests/application with riot_pal?

2019-10-18 14:52 UTC, jan-mo commented
ok I see the point. I thought it was also designed for other shell commands in RIOT.

We want to set different test-cases for the network interface. So than I use the riot_driver.py for sending and receiving messages, it will also work, I guess. 

Thanks

2019-10-21 08:50 UTC, MrKevinWeiss commented
Yup, you can also take a look at how [test_runner](https://github.com/RIOT-OS/RIOT/tree/master/dist/pythonlibs/testrunner) works which uses the make system and pexpect.  [Here](https://github.com/RIOT-OS/RIOT/blob/master/tests/gnrc_ipv6_ext/tests/01-run.py) is an example of it in action.

2019-10-21 14:12 UTC, smlng requested changes
sounds like this PR is invalid, and should be closed, right?

2019-10-21 14:25 UTC, jan-mo commented
Right, thanks.

2019-10-22 14:28 UTC, smlng commented
closing then

2019-10-22 14:28 UTC, closed without merging